<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RefMateriSeeder extends Seeder
{
    public function run(): void
    {
        // Data provided by user
        $data = [
            ['kategori' => 'English Course', 'materi' => 'English Course'],
            ['kategori' => 'Pameran', 'materi' => 'Pameran'], // Pameran not in Enum, keep as is or map? Enum limits EKSTRAKURIKULER table, but ref_materi might be used elsewhere? 
            // "Pendampingan Lomba" and "Sosialisasi" also not in Enum.
            // But for Ekstrakurikuler Sessions, we rely on the Enum.
            // I'll keep non-enum ones as is, but fix the ones that are definitely meant to match.
            ['kategori' => 'Pendampingan Lomba', 'materi' => 'Coding'],
            ['kategori' => 'Pendampingan Lomba', 'materi' => 'Robotika'],
            ['kategori' => 'Pendampingan Lomba', 'materi' => 'English Course'],
            ['kategori' => 'Sosialisasi bersama Sales', 'materi' => 'Coding'],
            ['kategori' => 'Sosialisasi bersama Sales', 'materi' => 'Robotika'],
            ['kategori' => 'Sosialisasi bersama Sales', 'materi' => 'English Course'],
            ['kategori' => 'Trial Class', 'materi' => 'Coding'],
            ['kategori' => 'Trial Class', 'materi' => 'Robotik'],
            ['kategori' => 'Trial Class', 'materi' => 'English Course'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Mengenal Bagian Menu Scratch'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Menyusun dan menjalankan perintah Scratch'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Membuat sprite bergerak (1)'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Membuat Sprite bergerak (2)'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Projek Game Saling Menembak'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Memahami Looks'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Mengendalikan Sprite Menggunakan Keyboard dan Mouse'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Membuat dan Mengubah Sprite di Menu Paint'],
            ['kategori' => 'Coding Scratch', 'materi' => 'PROJEK - Tikus Mencari Keju'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Memahami Variable'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Memahami menu Operator Matematika'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Projek : MIssion Target Pursuit'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Membuat Animasi Hujan'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Belajar Drag and Drop'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Projek - Bus Street'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Membuat Pola Garis Berwarna'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Membuat Garis Melengkung Berwarna-warni'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Membuat Scroll Backdrop Bergerak dari Atas ke Bawah'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Membuat Scroll Backdrop Bergerak dari Bawah ke Atas'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Projek - Pong Game'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Memahami menu utama dan ruang kerja.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Menjalankan perintah dengan blok kode sederhana.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Membuat proyek tombol tersenyum.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Memahami sensor gerak dan membuat ekspresi bergerak.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Melanjutkan proyek ekspresi bergerak.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Mengenal sensor cahaya dan konsep if-else.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Membuat proyek cahaya matahari.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Membuat proyek papan nama menggunakan teks.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Mengenal blok random dengan membuat dadu.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Melanjutkan proyek dadu Micro:bit.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Memahami logika kondisi dengan proyek gunting, batu, kertas.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Melanjutkan proyek gunting, batu, kertas.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Membuat proyek penghitung langkah kaki.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Melanjutkan dan menyempurnakan proyek penghitung langkah kaki.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Mengenal konsep variabel untuk data sederhana.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Membuat proyek dengan memanfaatkan variabel.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Merancang miniatur pohon natal dengan Lego dan LED.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Memasang resistor dan pin I/O pada proyek.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Menyempurnakan proyek Lego pohon natal.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Merancang miniatur portal dengan Lego dan servo.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Melanjutkan proyek Lego portal dengan mekanisme servo.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Menyempurnakan proyek Lego portal.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Membuat proyek gitar DIY menggunakan barang sekitar.'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Menyempurnakan dan mendemonstrasikan proyek gitar.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Pengenalan Micro:bit dan MakeCode, membuat proyek Flashing Heart.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Mengenal Jimu Trackbot beserta komponennya.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Mengenal komponen elektro seperti LED, resistor, dll.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Mengenal blok input seperti on start, forever, show icon, pause, dan sensor gerak.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Membuat proyek Emotion Badge.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Membuat proyek Dice menggunakan sensor akselerometer.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Membuat proyek Touch Emotion.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Mengenal sensor cahaya, membuat proyek Sunlight Sensor.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Membuat proyek Night Light dan menyelesaikan proyek tantangan.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Mengenal sensor suara melalui proyek Clap Heart.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Membuat proyek Pet Calling dan menyelesaikan proyek tantangan.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Memahami konsep repeat, while, if/else, dan comparison operators.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Dasar Scratch, menghubungkan dengan Micro:bit, dan membuat perintah suara.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Membuat proyek Compass Bearing dan Compass North.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Membuat proyek Rock, Paper, Scissors.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Membuat proyek Graphical Dice.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Membuat proyek Step Count.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Membuat portal Jimu, merakit, dan membuat kode.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Merakit proyek Jimu Grabberbot.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Memprogram dan menyelesaikan proyek tantangan Grabberbot.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Mengenal sensor radio melalui proyek SOS dan Teleporting Duck.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Mengenal sensor suhu dengan proyek Thermometer.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Membuat Indoor-Outdoor Thermometer dan proyek tantangan.'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Membuat smart trash bin mulai dari perancangan hingga pemrograman.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Membuat robot Lucky Cat sebagai pengantar dasar Jimu.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Membuat dan memprogram robot Vehicle.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Merakit robot Sumo Car untuk kompetisi sederhana.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Merakit dan memprogram robot humanoid sederhana.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Membuat robot Police Bot dengan fungsi sensor dasar.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Merancang sistem smart home sederhana menggunakan Jimu.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Membuat pintu otomatis dengan sensor pada robot.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Membuat robot Snail untuk eksplorasi mekanisme gerak lambat.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Mengembangkan Snail untuk lomba kecepatan kreatif.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Mengadakan tantangan robot Sumo untuk kompetisi antar siswa.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Membuat robot kursi roda sederhana dengan mekanisme gerak.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Merancang robot Sportbot untuk simulasi olahraga.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Membuat proyek jembatan robotik dengan kombinasi Lego.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Membuat robot Snake untuk simulasi pergerakan ular.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Merakit robot Grabberbot untuk fungsi menggenggam objek.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Tantangan Grabberbot untuk mengambil objek tertentu.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Merancang dan membuat robot Transformer dengan fitur transformasi.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Membuat robot Elephant Trunk dengan mekanisme unik.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Membuat penghalang otomatis menggunakan sensor dan servo.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Membuat robot Turtle untuk simulasi gerakan lambat.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Mengembangkan robot Turtle untuk lomba kecepatan kreatif.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Membuat robot Digbot untuk simulasi penggalian.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Merancang humanoid kustom sesuai ide kreatif siswa.'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Membuat proyek tempat tidur pintar dengan fungsi otomatis.'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Pengenalan Scratch & Interface'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Menyusun dan Menjalankan Perintah'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Membuat Sprite Bergerak (Gerak Dasar)'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Gerakan Lanjutan & Arah'],
            ['kategori' => 'Pictoblox AI', 'materi' => '🟩 Proyek Mini: Tembak-Tembakan'],
            ['kategori' => 'Pictoblox AI', 'materi' => '🟨 Kuis Interaktif Siswa'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Memahami Tampilan (Looks)'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Kontrol Sprite: Keyboard & Mouse'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Membuat dan Menggambar Sprite (Paint)'],
            ['kategori' => 'Pictoblox AI', 'materi' => '🟩 Proyek: Tikus Mencari Keju'],
            ['kategori' => 'Pictoblox AI', 'materi' => '🟦 Mini Proyek AI 1'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Memahami Variabel'],
            ['kategori' => 'Pictoblox AI', 'materi' => '🟨 Kuis Interaktif Siswa'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Operator Matematika'],
            ['kategori' => 'Pictoblox AI', 'materi' => '🟨 Review & Evaluasi Proyek Mini'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Proyek: Mission Pursuit'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Animasi Hujan'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Drag and Drop Dasar'],
            ['kategori' => 'Pictoblox AI', 'materi' => '🟩 Proyek: Bus Street'],
            ['kategori' => 'Pictoblox AI', 'materi' => '🟨 Kuis Interaktif Siswa'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Pola Garis Berwarna'],
            ['kategori' => 'Pictoblox AI', 'materi' => '🟦 Mini Proyek Non-AI 2'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Pola Garis Melengkung'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Scroll Backdrop Atas ke Bawah'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Scroll Backdrop Bawah ke Atas'],
            ['kategori' => 'Pictoblox AI', 'materi' => '🟩 Proyek Game: Pong'],
            ['kategori' => 'Pictoblox AI', 'materi' => '🟨 Kuis Interaktif Siswa'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Persiapan Proyek Final'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Presentasi Proyek Final'],
            ['kategori' => 'Pictoblox AI', 'materi' => '🟨 Evaluasi Akhir & Refleksi'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Mengenal menu utama, workspace, dan cara upload kode Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Menjalankan perintah dengan blok kode sederhana Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Membuat alarm getar sederhana Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Membaca suhu sekitar dengan Micro:bit Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Menampilkan suhu di layar Micro:bit Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Mengenal modul radio dan menghubungkan 2 Micro:bit Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Mengirim pesan antar Micro:bit Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Menerima pesan antar Micro:bit Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Mengontrol servo motor berdasarkan input sensor Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Merancang kunci pintu otomatis berbasis magnet Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Menyempurnakan proyek kunci pintu otomatis Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Kuis dan diskusi refleksi pemahaman Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Mengenal cara kerja sensor jarak dan membaca data Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Membuat alarm berbunyi saat objek mendekat Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Menyempurnakan alarm jarak Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Menghasilkan suara dengan Micro:bit Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Membuat nada musik berbasis sensor sentuh Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Menggabungkan nada menjadi musik sederhana Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Merancang pintu otomatis berbasis gerakan Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Menyempurnakan proyek pintu otomatis Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Membuat lampu otomatis sesuai intensitas cahaya Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Membuat smartwatch notifikasi getar Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Membuat kipas otomatis berbasis suhu ruangan Level 2'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Membuat jam digital interaktif Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa mengingat kembali fungsi dasar menu dan perintah di Scratch Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa membuat sprite mengikuti garis dengan perintah gerakan dan sensing Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa merancang dan membuat permainan labirin dengan rintangan dan logika pergerakan Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa menggunakan broadcasting untuk komunikasi antar-sprite Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa merancang dan membuat permainan perlombaan mobil dengan interaksi antar sprite Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa menggabungkan animasi sprite dengan efek suara interaktif Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa membuat game penangkapan dengan sistem skor Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa membuat game “Catch the Fruit” yang responsif terhadap input pengguna Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa belajar menerapkan penanganan kesalahan dalam proyek Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa merancang dan membuat game ular dengan kontrol berbasis input Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa membuat custom blocks untuk mengoptimalkan kode Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa membuat kalkulator dengan operasi matematika dasar Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa mengontrol sprite menggunakan input eksternal dari Makey Makey Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa merancang game berbasis sensor Makey Makey Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa membuat karakter berjalan di atas platform dengan kontrol pergerakan Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa membuat permainan platformer dengan beberapa level Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa memahami logika dan algoritma dasar game development Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa membuat game pencarian harta karun dengan logika dan rintangan Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa mengintegrasikan Microbit dengan Scratch untuk kontrol interaktif Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Siswa membuat permainan interaktif menggunakan Microbit sebagai pengontrol Level 2'],
            ['kategori' => 'Coding Scratch', 'materi' => 'Lain - Lain'],
            ['kategori' => 'Robotik Jimu', 'materi' => 'Lain - Lain'],
            ['kategori' => 'Pictoblox AI', 'materi' => 'Lain - Lain'],
            ['kategori' => 'Micro:bit Learning Kit', 'materi' => 'Lain - Lain'],
            ['kategori' => 'Robotik Explorer', 'materi' => 'Lain - Lain'],
        ];

        // DB::beginTransaction(); // Removed causing error with truncate
        try {
            DB::table('ref_materi')->truncate(); // Clean slate
            DB::table('ref_materi')->insert($data);
            // DB::commit();
        } catch (\Exception $e) {
            // DB::rollBack();
            throw $e;
        }
    }
}
